site_name: STMonitor
site_url: null
extra_css:
  - stylesheets/extra.css
theme:
  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.instant
    - toc.integrate
  favicon: images/favicon.png
  logo: images/logo2.png
  name: material
  scheme: default
  palette:
    primary: white
  font:
    text: Nunito Sans
    code: Fira Code
repo_url: https://github.com/chrisbartoloburlo/stmonitor
repo_name: chrisbartoloburlo/stmonitor
markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bartoloburlo
    - icon: fontawesome/brands/github
      link: https://github.com/chrisbartoloburlo
copyright: Copyright &copy; 2021 Christian Bartolo Burlò